on:
   workflow_dispatch:
   schedule:
     - cron: "0 9,10,16,17 * * 1-5"

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::jsonlite
            any::purrr

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Read data from portal
        run: Rscript -e 'source("src/r/data.R")'

      - name: Commit results
        run: |
          git config --local user.email " "
          git config --local user.name "NISRA-Tech-Lab"
          git add public/data/data.json
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"